language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"

  include:
  - os: osx
    language: generic
    python: "3.6"
    env: "TOXENV=py36"
    install:
      - brew update
      - brew upgrade python
      - python3 -m venv venv
      - source venv/bin/activate
      - pip3 install -r tests/requirements.txt
      - pip3 install -r requirements.txt
      - pip3 install -e .
    script: pytest -n 4 --cov --cov-config .coveragerc --cov-report xml --cov pyupdater --cov-append
  - os: osx
    language: generic
    python: "2.7"
    env: "TOXENV=py27"
    install:
      - brew update
      - brew uninstall --ignore-dependencies python
      - brew upgrade python@2
      - pip2 install virtualenv
      - python2 -m virtualenv venv
      - source venv/bin/activate
      - pip2 install -r tests/requirements.txt
      - pip2 install -r requirements.txt
      - pip2 install -e .
    script: pytest -n 4 --cov --cov-config .coveragerc --cov-report xml --cov pyupdater --cov-append


install:
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
  - pip install -e .
script: pytest -n 4 --cov --cov-config .coveragerc --cov-report xml --cov pyupdater --cov-append
after_success: codecov
deploy:
  provider: pypi
  user: JohnyMoSwag
  password:
    secure: 0iX3mRqMP3iShjTznKzNKXvn5SyYy2QkKILUV+hp8/J3SeNU9PohvoNRTaJM9iFSdAbi6KUg0uivRaFOpc9ctK2bEXjPx8tHQ8KBZ6WBks9inIrcP+OnaQBYIvTU2oPtn4SCDpgBGTem7NhACbZV3Ls/A2NyFB6ly5xwzox3vKyfdcYjmAujDciHIq/fKQ1CNNq3/ImGgKZcvmvm2ugs1zsa/QDoOL+ykwVA8HMbCF8JYqf2gPpyrqwEfvoMCqCqM7sj4ySqAjWsIAPuCdTidZVFNDsA3I/fLmuUbQprk9Yc613zxMW19PkDw7nFxyPmwwi2qLRNssL+bJ6xeN8Rv6kIjNzbkmWr0hjEgGN1Ni64+amyqDCrVtNpGN+R3SWzM4LNdddes9CXN//EynC7QUwpKs7kdWxsRSa6Zl5Nv3zYmDSx5at96s2Uk3AhhlnNxc9oZQXkaWaM6C1jHlQ0dqhI6deYKJCc0LjreCwb5hvIhPw+2eQdKDbPa1sn+iNF0eTspLJkeoJZ8CRPCkj5Wqluu/vymjqg0IhDokhUpdjTsPPk5NEuv5O8qR54O63We0UpqRjAg25k2AhLSwBJbNhi2TDr34d5ZdHs2ZElYdWbGuHsUMjkxUPOxO4xOM2738I7nMblntXBta0z/c37W60IIGb6HxmwK8OFnBKP87s=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: JMSwag/PyUpdater
    condition: $TRAVIS_PYTHON_VERSION=3.6
